@extends('layout.user')
@section('user')
    <h3>{{$user->name}}</h3>
    <!--form start-->
    <div class="container">
        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info btn-lg btn-group" data-toggle="modal" data-target="#myModal1">Profile</button>
        <button type="button" class="btn btn-info btn-lg btn-group" data-toggle="modal" data-target="#myModal2">New Offense</button>
        <button type="button" class="btn btn-info btn-lg btn-group" data-toggle="modal" data-target="#myModal3">All Offense</button>

        <div class="modal fade" id="myModal1" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">

                        <div class="row">
                            <div class="col-md-8">
                                @if($user)

                                        <div class="form-group">
                                            <label for="nic">NIC No </label>
                                            <input type="text" class="form-control" id=""  placeholder="" value="{{$user->id}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="name">Full Name</label>
                                            <input type="text" class="form-control" id=""  value="{{$user->name}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="oname">Other Names</label>
                                            <input type="text" class="form-control" id=""  value="{{$user->otherName}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="gender">Gender</label>
                                            <div class="form-control">
                                                <div class="form-check-inline">
                                                    <label class="form-check-label">
                                                        <input type="radio" class="form-check-input" name="gender" value="male" @if($user->gender=='male')
                                                        checked
                                                                @endif>Male
                                                    </label>
                                                </div>
                                                <div class="form-check-inline">
                                                    <label class="form-check-label">
                                                        <input type="radio" class="form-check-input" name="gender" value="female" @if($user->gender=='female')
                                                        checked
                                                                @endif>Female
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="birthday">Birthday</label>
                                            <input type="date" class="form-control" value="{{$user->bDay}}" >
                                        </div>
                                        <div class="form-group">
                                            <label for="address">Address</label>
                                            <input type="text" class="form-control" value="{{$user->address}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="phoneno">Phone No</label>
                                            <input type="text" class="form-control" value="{{$user->phoneNo}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email address</label>
                                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{$user->email}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="job">Job</label>
                                            <input type="text" class="form-control" value="{{$user->job}}">
                                        </div>

                                    @endif
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="nic">Image </label>
                                    <img src="images/user/{{$user->profileImage}}" alt="" width="100%" height="100%" class="img-thumbnail">
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="myModal2" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">New OFFENSE</h4>

                    </div>
                    <div class="modal-body">
                        @if(count($offense)>0)
                            @foreach($offense as $ofns)
                                @if($ofns->userId==$user->id && $ofns->notification==1)
                                    <a href="{{route('uoffense',['id'=>$ofns->id])}}">
                                        <div >
                                            <h6>{{$ofns->id}}</h6>
                                            <label >{{$ofns->pDiscription}}</label>
                                        </div>
                                    </a>
                                @endif
                            @endforeach
                        @endif
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="myModal3" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">All OFFense</h4>
                    </div>
                    <div class="modal-body">
                        @if(count($offense)>0)
                            @foreach($offense as $ofns)
                                @if($ofns->userId==$user->id)
                                    <a href="{{route('uoffense',['id'=>$ofns->id])}}">
                                        <div class=" @if($ofns->accept==2) bg-warning @elseif($ofns->accept==1) bg-danger @endif">
                                            <h6>{{$ofns->id}}</h6>
                                            <label >{{$ofns->pDiscription}}</label>
                                        </div>
                                    </a>
                                @endif
                            @endforeach
                        @endif
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
<p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
    fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
    Figure 1. The diagram of fingerprint acquisition circuits
    2010 First International Conference on Networking and Distributed Computing
    978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
    57
    2010 First International Conference on Networking and Distributed Computing
    978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
    57

    The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
    Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
    Figure3.  The initialization flow diagram of pressure sensitive control chip
    B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
    Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
    bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
    After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
    Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

    Figure4.  The flow chart of figerprint data  sampling start
    58 58

    -
    IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
    (a)                         (b)
    Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
    V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
    ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
    REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>
        <p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
            fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
            Figure 1. The diagram of fingerprint acquisition circuits
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57

            The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
            Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
            Figure3.  The initialization flow diagram of pressure sensitive control chip
            B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
            Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
            bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
            After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
            Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

            Figure4.  The flow chart of figerprint data  sampling start
            58 58

            -
            IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
            (a)                         (b)
            Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
            V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
            ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
            REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>
        <p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
            fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
            Figure 1. The diagram of fingerprint acquisition circuits
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57

            The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
            Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
            Figure3.  The initialization flow diagram of pressure sensitive control chip
            B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
            Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
            bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
            After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
            Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

            Figure4.  The flow chart of figerprint data  sampling start
            58 58

            -
            IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
            (a)                         (b)
            Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
            V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
            ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
            REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>
        <p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
            fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
            Figure 1. The diagram of fingerprint acquisition circuits
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57

            The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
            Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
            Figure3.  The initialization flow diagram of pressure sensitive control chip
            B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
            Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
            bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
            After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
            Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

            Figure4.  The flow chart of figerprint data  sampling start
            58 58

            -
            IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
            (a)                         (b)
            Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
            V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
            ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
            REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>
        <p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
            fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
            Figure 1. The diagram of fingerprint acquisition circuits
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57

            The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
            Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
            Figure3.  The initialization flow diagram of pressure sensitive control chip
            B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
            Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
            bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
            After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
            Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

            Figure4.  The flow chart of figerprint data  sampling start
            58 58

            -
            IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
            (a)                         (b)
            Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
            V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
            ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
            REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>
        <p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
            fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
            Figure 1. The diagram of fingerprint acquisition circuits
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57

            The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
            Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
            Figure3.  The initialization flow diagram of pressure sensitive control chip
            B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
            Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
            bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
            After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
            Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

            Figure4.  The flow chart of figerprint data  sampling start
            58 58

            -
            IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
            (a)                         (b)
            Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
            V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
            ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
            REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>
        <p>Abstract—This paper designs a complete fingerprint acquisition system which uses new-style of pressure sensitive fingerprint sensor chip BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. Keywords-fingerprint sensor; fingerprint acquisition; DSP5502; CCS; fingerprint identification I. INTRODUCTION Currently, owing to the unique and life-long invariance of fingerprint [1], it becomes the major biometrics research object. Additionally, fingerprint recognition technology also has high feasibility and practicality, so it is one of the most popular convenient and reliable technologies for personal identity authentication.  However, the development and application of domestic fingerprint identification products mainly use optical device to acquire fingerprint information. As the optical fingerprint sensor susceptible and easy to effect by the dirt and grease skin, there will be weak images for dry fingers, fuzzy images for more sweating, slightly swollen fingers [2-3]. Because of above shortcomings of optical devices, many products begin to be made by using semiconductor sensing devices acquire fingerprint images. Pressure-sensitive fingerprint acquisition sensor has pressure sensitive dielectric material on the surface, it relies on the finger pressing the surface of the sensing medium, due to the uneven finger prints arising of the different sizes pressure and convert into corresponding electrical signals to generate the fingerprint sensing images [1]. DSP (Digital signal processor) is the dedicated chip of digital signal processing; the combination of DSP and semiconductor fingerprint sensors has a wide application prospect in the embedded fingerprint identification system. This paper combine semiconductor chip small size, low power consumption, can be integrated into many existing devices and the advantages of DSP in embedded fingerprint identification system, uses pressure sensitive fingerprint sensor BLP100 and control chip BCT100 which produced by Japan's BMF, converts fingerprint information into DSP  for signal processing, the core processor chip of system using TI's TMS320C5502
            fingerprint data reading and processing, to achieve better effect than the optical acquisition devices. II. THE  DESIGN  OF  FINGERPRINT ACQUISITION  CIRCUITS A. Sensor BLP100 and Control chip BCT100 The design of the fingerprint acquisition circuit is mainly comprised of the fingerprint sensor BLP100 and fingerprint control chip BCT100 which produced by Japan's BMF. Fingerprint sensor BLP100 is a pressure sensitive semiconductor device which senses the pressure and passes into electronic signals thus generates fingerprint image data. The sensing area is 16.0×23.4mm, it is the world's first pressure sensitive fingerprint sensor, whether in water or in dry conditions can be the right perception without being effected, and the perceptional peak value below 3mA. The area of fingerprint control chip BCT100 is only 10mm×10mm，and the chip built-in 8-bit ADC ,accompanied by data bus, address bus, registers and other elements which can be easily used with BLP100.  B. Fingerprint acquisition circuits  When a finger presses the fingerprint sensor BLP100, BCT100 control the sensor BLP100 to acquire the fingerprint information and send the data to the A/D conversion. The data that has been converted will be sent to the DSP system and then waiting to process the stored image data. The diagram of fingerprint acquisition circuits as follows:
            Figure 1. The diagram of fingerprint acquisition circuits
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57
            2010 First International Conference on Networking and Distributed Computing
            978-0-7695-4207-2/10 $26.00 © 2010 IEEE DOI 10.1109/ICNDC.2010.21
            57

            The design uses the McBSP port of DSP5502 [4-5] to connect the fingerprint acquisition circuit; DSP (Digital signal processor) reads the fingerprint image data and process the following fingerprint recognition. Connection Type shown in Figure 2:
            Figure 2.  The diagram of acquisition circuits and DSP system connection Among them, the address bus (ABUS [4 ... 0]), data bus (DBUS [3 ... 0]), chip Enable (CE), write enable (WE), address of the chip enable (ACE terminal). III. DESIGN  AND  IMPLEMENTATION  OF PRESSURE SENSITIVE  F INGERPRINT  ACQUISITION SYSTEM   A. Initialization of fingerprint acquisition and the design of sampling The optimum application of fingerprint controller BCT100 depends on its right initialization. If the initialization fails, even if the acquisition function issues the ‘Start’ command for sampling, the system can not work properly. In the initialization process of software design, the first step is setting the fingerprint controller register CRST bit to 1, after waiting for 100ms, and then CRST set 0,only do this step it can be initialized. The initialization flow diagram of pressure sensitive control chip as follows:
            Figure3.  The initialization flow diagram of pressure sensitive control chip
            B. The implementation of acquisition system software CCS IDE (Code Composer Studio Integrated
            Development Environment) is dedicated development environment of DSP which integrates software development, compile, link and other functions etc. So the design of controlling initialization and sampling software are completed in the CCS development environment.  By editing the function’Fun_Sensor_init(void)’ in the CCS IDE, we can initialize the fingerprint sensor BLP100; and by setting and calling the delay function’ Fun_delay_ms(void)’,’ Fun_delay_1us(void)’ that ensure BCT100 be initialized correctly. The initialization flow diagram of pressure sensitive control chip as figure3, and part of the initialization program are as follows:
            bool  Fun_Sensor_init(void) {   ……    Bmf_reset_lo;    …….   Bmf_Address = Bmf_NHST_1;    Bmf_Address = Bmf_CRST_1;   Fun_delay_1us (); ……  }
            After the program is initialized normally, through design the acquisition function’Fun_Get_BmfImage (uint8 *pImage)’, we can get and transmit the fingerprint image data. The flow chart of figerprint data sampling start as figure4, and parts of the program are as follows:
            Fun_Get_BmfImage(uint8 *pImage)    {   ……    for (r_i = 0; r_i <384; r_i++)         { ……       xsed = 1;       while (xsed == 1) {  xsed = Bmf_sed; }     ……  }   ……   }

            Figure4.  The flow chart of figerprint data  sampling start
            58 58

            -
            IV. EXPERIMENTAL RESULTS AND ANALYSIS As the BLP100 and BCT100 use control technology which can automatically adjust the fingerprint image acquisition line and the sensitivity of the local scope area. Through the system hardware design, initialization of the fingerprint image acquisition software design and acquisition program design, the fingerprint acquisition system gets high-quality fingerprint data.  The acquired fingerprint image as Figure 4(a), making it normalized and filtered in fingerprint recognition system of vc6.0 environment [6], and the normalized and filtered fingerprint image as Figure 4 (b).  The experimental result shows that this system can successfully provide high-quality fingerprint image information for the following fingerprint identification; more importantly, it also provides an efficient solution for living fingerprint acquisition.
            (a)                         (b)
            Figure4.  Comparison of fingerprint images  (a) The acquired fingerprint image   (b) Normalized and filtered fingerprint image With the development of society and the improvement of our life, information security has become increasingly important, and the fingerprint identification system will have a more broad application prospect.
            V. CONCLUSION  This paper designs the fingerprint acquisition system by using the semiconductor pressure sensitive fingerprint sensor BLP100 and fingerprint control chip BCT100. The system has characteristics of simple structure, fast capturing speed, high quality image, connecting with external processor easily and so on. Compared with the original images, the images that acquired by this system have been normalized and filtered, and the result shows that this system can obtain the fingerprint image information more easily and reliably. In addition, it can be well converted to the following fingerprint processing and authentication which is suited for embedded system applications
            ACKNOWLEDGMENT This article would have not been possible without the assistance and encouragement of numerous individuals who helped me a lot. Should these people be not around, it would have been very difficult and it may have been unfeasible to have the output. Thus, it is my pleasure to take this opportunity to give thanks and offer sincerest gratitude to them.
            REFERENCES [1] H. R. Wu. Fingerprint technology and development trends [J].Information Technology,2009,217(14):258. [2] Y. B. Ke. Fingerprint acquisition system DSP-based [D].Hubei: Technology automation College of Wuhan University, 2006 [3] H. Chen. Fingerprinting technology and its development prospects [J].Security vision. 2008,5(01):26-31 [4] A. M. Wang, Y. Chen, B. G. Xu. The study typical case of DSP embedded system [M]. Beijing: Posts &Telecom Press, 2007 [5] S. W. Zhang. DSP-based Fingerprint Acquisition System [J]. Wuhan University of Technology,2007,29(5):40-43. [6] J. Huang, D. Wang. Pressure sense fingerprint identification </p>

    </div>

    <!--form end-->
@endsection